In [90]:
import pandas as pd
import wget
import numpy as np
import platform


In [91]:
print(platform.python_version())

3.12.4


Q1: python version 3.12.4

In [8]:
url = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv'

In [9]:
wget.download(url)

'car_fuel_efficiency.csv'

In [13]:
df = pd.read_csv('car_fuel_efficiency.csv')

In [14]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [15]:
df.describe()

engine_displacement  num_cylinders   horsepower  vehicle_weight  \
count          9704.000000    9222.000000  8996.000000     9704.000000   
mean            199.708368       3.962481   149.657292     3001.280993   
std              49.455319       1.999323    29.879555      497.894860   
min              10.000000       0.000000    37.000000      952.681761   
25%             170.000000       3.000000   130.000000     2666.248985   
50%             200.000000       4.000000   149.000000     2993.226296   
75%             230.000000       5.000000   170.000000     3334.957039   
max             380.000000      13.000000   271.000000     4739.077089   

       acceleration   model_year    num_doors  fuel_efficiency_mpg  
count   8774.000000  9704.000000  9202.000000          9704.000000  
mean      15.021928  2011.484027    -0.006412            14.985243  
std        2.510339     6.659808     1.048162             2.556468  
min        6.000000  2000.000000    -4.000000             6.200971  
25%       13.300000  2006.000000    -1.000000            13.267459  
50%       15.000000  2012.000000     0.000000            15.006037  
75%       16.700000  2017.000000     1.000000            16.707965  
max       24.300000  2023.000000     4.000000            25.967222

In [17]:
df.shape[0]

9704

Q2: 9740 number of records

In [18]:
df.columns

Index(['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'model_year', 'origin', 'fuel_type', 'drivetrain',
       'num_doors', 'fuel_efficiency_mpg'],
      dtype='object')

In [20]:
df['fuel_type'].nunique()

2

Q3: 2 fuel types

In [21]:
df.isnull().any().sum()

4

In [22]:
df.columns[df.isnull().any()].tolist()

['num_cylinders', 'horsepower', 'acceleration', 'num_doors']

Q4: 4 columns have missing values

In [30]:
df['origin'].unique()

array(['Europe', 'USA', 'Asia'], dtype=object)

In [31]:
df[df['origin']=='Asia']['fuel_efficiency_mpg'].max()

23.759122836520497

Q5. 23.75

In [35]:
#median value
df['horsepower'].median()

149.0

In [38]:
#the most frequent value
most_freq = df['horsepower'].mode()[0]

In [40]:
df['horsepower'] =df['horsepower'].fillna(most_freq)

In [41]:
#median value after changes
df['horsepower'].median()

152.0

Q6. Yes, it increased

In [42]:
asian_cars = df[df['origin']=='Asia']

In [44]:
asian_cars = asian_cars[['vehicle_weight','model_year']]

In [46]:
top_7 =asian_cars.head(7)

In [75]:
X = top_7.to_numpy()

In [76]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [77]:
X.T

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [78]:
XTX = X.T @ X

In [79]:
XTX 

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [80]:
XTX.T

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [82]:
XTX = np.linalg.inv(XTX)

In [52]:
y = np.array([[1100, 1300, 800, 900, 1000, 1100, 1200]])

In [83]:
w = (XTX @ X.T)*y

In [84]:
w

array([[-0.14432288, -0.11230828,  0.29810794, -0.36245398, -0.16251372,
        -0.06075771,  0.55811286],
       [ 0.28890053,  0.2560879 , -0.37871378,  0.59305003,  0.30835783,
         0.16679975, -0.72957556]])

In [85]:
np.sum(w)

0.5187709081074016

Q7 Sum of weights = 0.51